"use strict";
const state={manifest:null,records:[],filtered:[],selected:null,page:1,pageSize:10},$=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])),unique=(r,k)=>[...new Set(r.map(x=>x.finding?.[k]??"unknown"))].sort();
function setQuery(){const p=new URLSearchParams();for(const id of["search","role","status","confidence"])if($(id).value)p.set($(id).name,$(id).value);p.set("page",state.page);history.replaceState(null,"",`${location.pathname}?${p}#findings`)}
const metric=(l,v,f="",x="")=>`<button class="metric" data-filter="${f}" data-value="${x}"><span>${esc(l)}</span><strong>${esc(v)}</strong></button>`;
function renderOverview(){const m=state.manifest,r=state.records,roles={};r.forEach(x=>{const k=x.finding?.role||"unknown";roles[k]=(roles[k]||0)+1});$("metrics").innerHTML=metric("Files scanned",m.files_scanned??0)+metric("Files skipped",m.skipped_files??0)+metric("Operations / findings",r.length)+metric("Unknown roles",roles.unknown||0,"role","unknown");$("roles").innerHTML=Object.entries(roles).sort().map(([k,v])=>`<button class="pill ${k==="unknown"?"unknown":""}" data-filter="role" data-value="${esc(k)}">${esc(k)} · ${v}/${r.length}</button>`).join("");document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{if(b.dataset.filter){$(b.dataset.filter).value=b.dataset.value;state.page=1;applyFilters();location.hash="findings"}})}
function populate(){for(const[id,k]of[["role","role"],["status","status"],["confidence","confidence"]])for(const v of unique(state.records,k))$(id).insertAdjacentHTML("beforeend",`<option value="${esc(v)}">${esc(v)}</option>`);const p=new URLSearchParams(location.search);for(const[id,key]of[["search","q"],["role","role"],["status","status"],["confidence","confidence"]])$(id).value=p.get(key)||"";state.page=Math.max(1,Number(p.get("page"))||1)}
function applyFilters(){const q=$("search").value.toLowerCase(),role=$("role").value,status=$("status").value,confidence=$("confidence").value;state.filtered=state.records.filter(r=>{const f=r.finding||{},hay=JSON.stringify(r).toLowerCase();return(!q||hay.includes(q))&&(!role||f.role===role)&&(!status||f.status===status)&&(!confidence||f.confidence===confidence)});const pages=Math.max(1,Math.ceil(state.filtered.length/state.pageSize));state.page=Math.min(state.page,pages);setQuery();renderRows(pages)}
function renderRows(pages){const rows=state.filtered.slice((state.page-1)*state.pageSize,state.page*state.pageSize);$("result-count").textContent=`${state.filtered.length} of ${state.records.length} records · page ${state.page} of ${pages}`;$("finding-rows").innerHTML=rows.map(r=>{const f=r.finding||{},p=r.plan||{},l=f.location||{},d=p.decision_trace?.outcome||(p.requires_manual_intervention?"abstain":"recommend");return`<tr tabindex="0" data-id="${esc(f.id)}"><td class="location">${esc(l.file_path)}:${esc(l.line_number)}</td><td>${esc(f.primitive_name)}</td><td>${esc(f.role)} / ${esc(f.operation)}</td><td>${esc(f.status)}</td><td>${esc(f.confidence)}</td><td class="decision-${d}">${esc(d)}</td></tr>`}).join("")||'<tr><td colspan="6" class="empty">No matching findings.</td></tr>';document.querySelectorAll("tbody tr[data-id]").forEach(row=>{const go=()=>selectRecord(row.dataset.id);row.onclick=go;row.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();go()}}});$("page").textContent=`${state.page} / ${pages}`;$("previous").disabled=state.page<=1;$("next").disabled=state.page>=pages}
function card(t,b){return`<div class="card"><b>${t}</b>${b}</div>`}async function selectRecord(id){state.selected=state.records.find(r=>r.finding?.id===id);const r=state.selected,f=r.finding||{},p=r.plan||{},l=f.location||{};$("evidence-body").innerHTML='<div class="card-grid">'+card("Location",`<p class="location">${esc(l.file_path)}:${esc(l.line_number)}:${esc(l.column??0)}</p><button id="open-source">Open local excerpt</button>`)+card("Observed evidence",`<p>${esc(l.context_snippet||"No excerpt stored")}</p><p>${esc(f.context_evidence||"No contextual inference")}</p>`)+card("Classification",`<p>${esc(f.detection_type)} · ${esc(f.protocol_context||"unknown")}</p><p>Finding ${esc(f.id)}</p>`)+card("Rule provenance",`<p>${esc(p.rule_id||"No matched rule")} · ${esc(p.rule_version||"unknown")}</p><p>Trace ${esc(p.decision_trace?.trace_id||"not available")}</p>`)+"</div>";$("planner-body").innerHTML='<div class="card-grid">'+card("Proposed family",`<p>${esc(p.target_algorithm||"UNKNOWN")}</p><p>${esc(p.target_standard||"N/A")}</p>`)+card("Decision",`<p>${p.requires_manual_intervention?"ABSTAIN / MANUAL":"ADVISORY RECOMMENDATION"}</p><p>${esc(p.intervention_reason||"Review prerequisites before any change.")}</p>`)+card("Blockers",`<p>${(p.blocker_codes||[]).map(x=>`<span class="pill">${esc(x)}</span>`).join(" ")||"None recorded"}</p>`)+card("Priority dimensions",`<pre>${esc(JSON.stringify(p.priority||{},null,2))}</pre>`)+"</div>";$("source").hidden=true;$("open-source").onclick=()=>loadSource(l.file_path,l.line_number);location.hash="evidence"}
async function loadSource(path,line){const pre=$("source");try{const res=await fetch(`/api/source?path=${encodeURIComponent(path)}&line=${line}`),body=await res.json();if(!res.ok)throw Error(body.error);pre.textContent=body.lines.map(x=>`${x.selected?">":" "} ${String(x.number).padStart(4)} | ${x.text}`).join("\n")}catch(e){pre.textContent=`Source unavailable: ${e.message}`}pre.hidden=false}
const badge=s=>`<span class="status status-${esc(s)}">${esc(String(s).replace("_"," "))}</span>`;
async function getJson(url){const r=await fetch(url),b=await r.json();if(!r.ok)throw Error(b.error||`HTTP ${r.status}`);return b}
async function renderD16(){
  try{const p=await getJson("/api/patch-preview"),policy=p.mutation_policy||{};$("patch-body").className="";$("patch-body").innerHTML=`<div class="banner ${p.eligible_for_apply?"pass":"not-run"}">${p.eligible_for_apply?"Eligible":"Preview only — apply refused"} · ${esc(p.status)}</div><div class="card-grid">${card("Scope",`<p>${esc(p.transformation_id||"No preview generated")}</p><p>${esc(p.source_path||"")}:${esc(p.line_number||"")}</p>`)}${card("Requirements",`<p>${esc((p.blocker_codes||policy.blocker_codes||[]).join(", ")||"No blockers recorded")}</p>`)}${card("Risk summary",`<p>${esc(p.compatibility_warning||p.explanation||"No evidence available")}</p>`)}</div><h3>Unified diff</h3><pre class="source">${esc(p.diff||"No diff available.")}</pre>`}catch(e){$("patch-body").className="error";$("patch-body").textContent=`Patch evidence error: ${e.message}`}
  try{const a=await getJson("/api/assurance");$("assurance-body").className="";$("assurance-body").innerHTML=`<div class="card-grid">${a.stages.map(s=>card(s.name,`${badge(s.status)}<p>Reported: ${esc(s.reported_status)}</p>`)).join("")}${card("Provenance",`<p>Source commit: <code>${esc(a.source_commit)}</code></p><p>Patch hash: <code>${esc(a.patch_hash||"not available")}</code></p>`)}${card("Checks and environment",`<pre>${esc(JSON.stringify({checks:a.checks,command:a.test_command,exit_code:a.test_exit_code,environment:a.environment},null,2))}</pre>`)}</div><h3>Limits / failures</h3><ul>${(a.limitations||[]).map(x=>`<li>${esc(x)}</li>`).join("")||"<li>No limitation evidence recorded.</li>"}</ul>`}catch(e){$("assurance-body").className="error";$("assurance-body").textContent=`Assurance error: ${e.message}`}
  try{const c=await getJson("/api/compare");$("compare-body").className="";$("compare-body").innerHTML=`<div class="banner ${c.status==="compared"?"pass":"not-run"}">${esc(c.status==="compared"?"Two-manifest comparison":"Comparison not run — start with --compare PREVIOUS.json")}</div><div class="metrics">${metric("New",c.new.length)+metric("Resolved",c.resolved.length)+metric("Unchanged",c.unchanged.length)}</div><pre>${esc(JSON.stringify(c.coverage,null,2))}</pre>`}catch(e){$("compare-body").className="error";$("compare-body").textContent=`Comparison error: ${e.message}`}
}
async function init(){try{const res=await fetch("/api/manifest");if(!res.ok)throw Error(`HTTP ${res.status}`);state.manifest=await res.json();state.records=state.manifest.records||[];$("provenance").textContent=`schema ${state.manifest.schema_version||"?"} · scan ${state.manifest.scan_id||"?"} · commit ${state.manifest.source_commit||"unknown"}`;populate();renderOverview();applyFilters();$("filters").oninput=()=>{state.page=1;applyFilters()};$("previous").onclick=()=>{state.page--;applyFilters()};$("next").onclick=()=>{state.page++;applyFilters()}}catch(e){$("provenance").textContent=`Manifest error: ${e.message}`}renderD16()}init();
