#!/usr/bin/env python3
"""
sync_sample_summary.py
======================
Reads the canonical three-fixture-report.json and regenerates
website/data/sample-summary.json so test_d17_website.py passes
on repeated runs without manual editing.

Run after any strict validation that regenerates the three-fixture report:
    python3 scripts/sync_sample_summary.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).parents[1]
MANIFEST_PATH = ROOT / "review-artifacts" / "latest" / "three-fixture-report.json"
SAMPLE_PATH   = ROOT / "website" / "data" / "sample-summary.json"


def main() -> int:
    if not MANIFEST_PATH.exists():
        print(f"ERROR: manifest not found: {MANIFEST_PATH}", file=sys.stderr)
        return 1

    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    records   = manifest.get("records", [])
    decisions = [
        (r.get("plan") or {}).get("decision_trace", {}).get("outcome")
        for r in records
    ]

    sample = {
        "schema_version":  manifest.get("schema_version", ""),
        "scan_id":         manifest.get("scan_id", ""),
        "source_commit":   manifest.get("source_commit", ""),
        "files_scanned":   manifest.get("files_scanned", 0),
        "finding_count":   len(records),
        "recommend_count": decisions.count("recommend"),
        "abstain_count":   decisions.count("abstain"),
        "_note": (
            "Auto-generated by scripts/sync_sample_summary.py "
            "from review-artifacts/latest/three-fixture-report.json. "
            "Do not edit manually."
        ),
    }

    SAMPLE_PATH.parent.mkdir(parents=True, exist_ok=True)
    SAMPLE_PATH.write_text(
        json.dumps(sample, indent=2) + "\n",
        encoding="utf-8",
    )

    print(f"Wrote {SAMPLE_PATH}")
    print(f"  scan_id        : {sample['scan_id']}")
    print(f"  source_commit  : {sample['source_commit']}")
    print(f"  files_scanned  : {sample['files_scanned']}")
    print(f"  finding_count  : {sample['finding_count']}")
    print(f"  recommend_count: {sample['recommend_count']}")
    print(f"  abstain_count  : {sample['abstain_count']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
